version: 0.2

env:
  parameter-store:
    ENV1: "/stg/REACT_APP_GOOGLE_API"
    ENV2: "/stg/REACT_APP_IOS_APP_ID"
    ENV3: "/stg/REDIS_SERVER_URL"
phases:
  install:
    commands:
      - apt-get update
      - apt install jq
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo $ENV1
      - echo $ENV2
      - echo $ENV3
      - envsubst < template-env.yaml > .env
      - cat .env
      - echo Building the Docker image...
      - aws ecr get-login-password --region ap-northeast-1 | docker login -u AWS --password-stdin 188492694258.dkr.ecr.ap-northeast-1.amazonaws.com/hizakurige-basic-image-repository-stg:nginx-latest-1.19
      - docker build -t test:latest .
      - docker tag test:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo $REPOSITORY_URI:$IMAGE_TAG
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 188492694258.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - envsubst < appspec_template.yaml > appspec.yaml

      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
